### PR TITLE
convert print to warnings.

### PR DESCRIPTION
**Pull request by rainwoodman**
avoid interfering with stdout in a non-controlable way.

### CODE REVIEW

**Comment by esheldon** [comment]
that is not a warning, it is informative.

**Comment by esheldon** [comment]
I mean this one
```python
print('Removing existing file')
```

**Comment by rainwoodman** [comment]
I understand.

but a library shall not make assumptions on how a user utilizes stdout.
warnings is a friendlier way to issue informative notes from a library. 

As an example, if fitsio io is used in a cgi-bin script. that message would be forcely written to the webpage at the point a FITS object is created.

1. If user cares about this information it can be collected via warnings.catch_warnings (see the test case)
2. If user doesn't care about this, it can be suppressed
3. If user doesn't do anything, the warning will be issued on stderr, and stdout is untainted.

Besides, it is just replacing the call to print_function to a call to warnings.warn.

**Comment by esheldon** [comment]
good point about the cgi script

**Comment by esheldon** [comment]
This is way too verbose though

>>> fitsio.write('test.fits',zeros(30),clobber=True)
/home/esheldon/exports/fitsio-local/lib/python2.7/site-packages/fitsio/fitslib.py:318: FITSRuntimeWarning: Removing existing file
  warnings.warn('Removing existing file', FITSRuntimeWarning)

I don't want to see that a thousand times.  Is there a way to make this less chatty?

**Comment by esheldon** [comment]
there is another problem: it only gets printed once.  The user needs to see this every time a file gets clobbered.

**Comment by esheldon** [comment]
How about printing to stderr?

**Comment by rainwoodman** [comment]
I added two commits to print the caller:

```
python test.py
test.py:43: FITSRuntimeWarning: Removing existing file: `/scratch1/scratchdirs/yfeng1/fitsio-ImageWrite-gMBvnU.fits`
  with fitsio.FITS(fname,'rw',clobber=True) as fits:
ok
```
Because of the added filename, each violation shall be a separate line. 

I would always deal with overwriting in the caller and decide to print to stderr or stdout there. 
From the semantics of the arguments, if 'clobber==True', it is probably safe to assume the caller  already wants to overwrite the file.

**Pull request merged**
