### PR TITLE
BUG fix deprecation warnings

### LINKED ISSUE #291: Deprecation warnings on keys doesn't make sense?
With the latest version (1.1) a whole bunch of deprecation warnings have appeared that I don't understand.
E.g., the following script:
```
$ cat deptest.py
import fitsio
import numpy as np

test = np.zeros(10)

fitsio.write('warningtest.fits', test)
```
And then if I run `python -Wd deptest.py` (python 3.7.6) I get a whole bunch of:
```
[...]/python3.7/site-packages/fitsio/fitslib.py:354: DeprecationWarning: The keyword arguments '%s' are being ignored! This warning will be an error in a future version of `fitsio`!
```
The problem seems to be that `**keys` is an empty dictionary, which I think is as it should be, but `not keys` resolves to `True` which triggers a warning.  On top of that, I don't know how to interpret the unfilled `%s` in the deprecation warning.

### PR DESCRIPTION
**Pull request by beckermr**
I messed up. Now I am paying my penance.
 
Closes #279 
Closes #291

### CODE REVIEW

**Comment by beckermr** [comment]
@erykoff can you try this branch out?

**Comment by erykoff** [comment]
Looks good to me.  Thanks!

**Comment by beckermr** [comment]
@esheldon this is ready for review

**Comment by esheldon** [comment]
looks good

**Pull request merged**
