### PR TITLE
Fpack in filename

### LINKED ISSUE #283: Fpack compression stopped working?
Hi,

In fitsio 0.9.12, this code:
```
import fitsio
import numpy as np
img = np.zeros((1000,1000), np.float32)
fitsio.write('/tmp/test.fits.fz[compress R 100,100; qz -1e-4]', img, clobber=True)
```
produces a FITS file that is fpack compressed.

In fitsio 1.0.5, the same code results in a non-compressed file.

Also, `clobber=True` doesn't work in the latter case.

This is in python3, with fitsio installed on a fresh ubuntu 18.04 container using
pip3 install fitsio==0.9.12
or
pip3 install fitsio==1.0.5

cheers,
--dustin

### PR DESCRIPTION
**Pull request by esheldon**
closes #283

### CODE REVIEW

**Comment by beckermr** [comment]
This change will reintroduce the bug that it solved here: https://github.com/esheldon/fitsio/issues/150

**Comment by beckermr** [comment]
Or at least we should test.

**Comment by esheldon** [comment]
that fix is what introduced this bug :)

**Comment by esheldon** [comment]
looking at this, it is the convention for cfitsio that compression stays on until you turn it off, so it was doing the expected thing before, from a historical perspective

**Comment by esheldon** [comment]
@sbailey

**Comment by beckermr** [comment]
> that fix is what introduced this bug :)

So we have to turn it off in the code in order to not reintroduce the issue where if you write one image, the subsequent ones get compressed too. Otherwise we need to reopen #150.

**Comment by esheldon** [comment]
right, these are totally incompatible basically.  If I had looked into #150 more I would have seen that we should not have "fixed" it

**Comment by esheldon** [comment]
but... it does mean we should add the ability to turn off compression when writing a new hdu

**Comment by beckermr** [comment]
I think we have to do it automatically somehow...

**Comment by moustakas** [comment]
Thanks @esheldon! I've tested and this PR works. I suspect @sbailey won't care if we defer a fix for #150 to a different PR, so this can get merged. (And if you could cut a `1.0.6` tag...)

**Comment by esheldon** [comment]
@beckermr  I think I'm not being clear.  In cfitsio land you have to turn it off "by hand", and by putting in the fix for #150 we broke that, and broke the "compression in filename" as well.

Basically that "bug" was a "feature" and we screwed up by fixing it.

**Comment by beckermr** [comment]
Ahhhh. If we want to emulate the cfitsio interface, then great. We should provide a hook to turn it off at the python level.

**Comment by esheldon** [comment]
That's the idea, but I would like to get feedback from @sbailey

**Comment by sbailey** [comment]
If fitsio provides a way to turn compression back off after writing one compressed image, I think that would be sufficient.  It was the enforced "once compressed always compressed" feature/bug that was problematic.  Our particular use case was that we wanted to write integer images (masks) as compressed since it is lossless, but did *not* want to write subsequent float images as compressed because that was lossy, and then tripped over this problem.

**Comment by beckermr** [comment]
Sounds good. A context manager for this might ideal

```python

import fitsio

f = fitsio.FITS(...)

with f.compressed():
    # do something with f

```

**Comment by dstndstn** [comment]
echoing @moustakas , we would super appreciate it if you could merge and tag a release with this fix!

**Comment by esheldon** [comment]
should we wait until the option to turn the compression off is implemented?

**Comment by moustakas** [comment]
Restoring the compression option functionality is far higher priority for
DESI right now.

**Pull request merged**
