### PR TITLE
Add support for X (bit) binary table column type

### PR DESCRIPTION
**Pull request by taldcroft**
This addresses #80.

This passes the initial requirement of reading the file mentioned in #80.  

I got stuck on how to write a test for this within the existing test framework.  From what I can see that needs to write a FITS table based on an existing table.  Then I couldn't immediately figure out what to change in order to write an `X` type column.  `astropy.io.fits` punts on this and writes out `L`.  From an API perspective it seems like there is some ambiguity about how to write out a numpy `b1` dtype object (either `L` or `X`).

### CODE REVIEW

**Comment by esheldon** [comment]
this worked, without modifying other code?

**Comment by taldcroft** [comment]
It apparently works (which also surprised me).
```
In [1]: import fitsio

In [2]: t = fitsio.read('test.fits')

In [3]: t[0]
Out[3]: (567995626.477488, [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False])

In [4]: t.dtype
Out[4]: dtype([('TIME', '>f8'), ('QUALITY', '?', (263,))])
```

**Comment by taldcroft** [comment]
@esheldon - apologies, I wasn't expecting you to merge this prior to having formal tests that pass.  I was working on that this afternoon when I discovered a problem.  It turns out that while the first row has the correct values, the subsequent rows of a different column are corrupted.
```
In [1]: import fitsio
In [2]: t = fitsio.read('test_x.fits')
In [4]: from astropy.io import fits
In [5]: hdus = fits.open('test_x.fits')

In [8]: t['TIME']
Out[8]: array([  5.67995626e+008,  -1.98263180e+219,   0.00000000e+000])

In [9]: hdus[1].data['TIME']
Out[9]: array([  5.67995626e+08,   5.67995629e+08,   5.67995631e+08])
```
You can reproduce this with the `test_x.fits` file that is now in this branch.  So I confess to being a bit stuck now in terms of where to go from here.  I know only enough about the Python C API to recognize the basic structures, but I have very little practical experience debugging it, and I haven't directly used CFITSIO in many years.

**Comment by esheldon** [comment]
OK, I just temporarily commented it out.  We can explore further.  Please stick to the branch.

**Pull request merged**
