### PR TITLE
BUG fix latest segfault

### PR DESCRIPTION
**Pull request by beckermr**
This PR fixes the latest segfault for headers.

### CODE REVIEW

**Comment by dstndstn** [comment]
The bug from #302 is fixed, but #325 still fails
```
> python -c "import fitsio; print(fitsio.__version__); fitsio.read_header('/tmp/bad-teeny.fits'); print('1'); fitsio.read_header('/tmp/tiny.fits')"
1.1.4
1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dstn/fitsio/fitsio/fitslib.py", line 238, in read_header
    return FITSHDR(_fits.read_header(hdunum))
OSError: FITSIO status = 202: keyword not found in header

```

**Comment by beckermr** [comment]
Yup that is to be expected. We will need this and the PR from @esheldon.

**Comment by beckermr** [comment]
I've pushed the changes from @esheldon into this branch. Can you try again?

**Comment by beckermr** [comment]
Both of the files work for me now. We need to write a test for the segfault.

**Comment by dstndstn** [comment]
I confirm that both work for me!

**Comment by dstndstn** [comment]
(though the header changes from "FRA.ZP" to "FRAKZP"...)

**Comment by beckermr** [comment]
Right. We'll need to fix that in another PR.

**Comment by beckermr** [comment]
I've checked that the test I added fails without this PR.

**Comment by beckermr** [comment]
@esheldon I merged your PR #329 into this PR and added a segfault bug. I think both should be merged and then we can work on parsing to something better than we are now.

**Comment by beckermr** [comment]
@dstndstn Are you ok if we ship the contents of the header you provided as part of the fitsio test suite under its license?

**Comment by dstndstn** [comment]
Yes, that's fine, thank you for asking (and for all this work!).

**Comment by esheldon** [comment]
If I followed the discussion, we will discuss how to replace JUNK___ in another issue/PR.

If so then this is ready to go

**Review by esheldon — APPROVED** [review]

**Pull request merged**
