### PR TITLE
ensure extname is ascii

### LINKED ISSUE #345: The extension name is wrongly sanitized
Hi,

I think I found a bug, and associated fix ;-)

As of today, it is possible to create an extension named `A.B` (which is valid), but the name is parsed as `A_B` at read-time (which is wrong).

In [PyFITSObject_get_hdu_info](https://github.com/esheldon/fitsio/blob/master/fitsio/fitsio_pywrap.c#L694) the `extname` variable -- which I think holds the value of the EXTNAME keyword -- is sanitized by [convert_keyword_to_allowed_ascii](https://github.com/esheldon/fitsio/blob/master/fitsio/fitsio_pywrap.c#L89).

This function converts everything which is not a letter or digit or `-` to `_`. Yet, it seems to me that all ASCII characters are valid as keyword *values*, like the dot, and the function should only be applied to keyword *names*. Or did I completely miss something?

Hope it helps!

### PR DESCRIPTION
**Pull request by esheldon**
closes #345

### CODE REVIEW

**Comment by esheldon** [comment]
@kabasset

**Comment by beckermr** [comment]
I may be the culprit here for this bug. Sorry.

**Comment by kabasset** [comment]
@esheldon Thanks a lot for the quick fix!

**Review by beckermr — COMMENTED** [review]
We may want to edit the function name given it is only used for hdu and ext names now.

**Comment by beckermr** [comment]
Ack I missed that. Sorry!

**Pull request merged**
