### PR TITLE
Convert testing to pytest

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by esheldon** [comment]
@beckermr do you know how to pass the "--use-system-fitsio" stuff when using pip?

**Comment by esheldon** [comment]
Looks like I got it right. Not well documented.

**Comment by esheldon** [comment]
Not sure why it works on some python versions and not others

**Comment by beckermr** [comment]
there are errors due to 

```
           ref = importlib.resources.files("fitsio") / 'test_images' / 'test_gzip_compressed_image.fits.fz'  # noqa
E           AttributeError: module 'importlib.resources' has no attribute 'files'
```

Older versions of python do not support this.

**Comment by esheldon** [comment]
Thanks

**Review by beckermr — APPROVED** [review]

**Pull request merged**
