### PR TITLE
Add Travis-CI OSX build/installation tests

### PR DESCRIPTION
**Pull request by rainwoodman**
This PR adds build/installation tests on mac. 

NOTE: These tests assert that via 'lastest' version of conda, fitsio builds and installs on OSX. (linux tests are also based on conda.)

This may conflict with the cfitsio_build_ext branch, but I will add these to the branch such that when merging .travis.yml there shall be used.

### CODE REVIEW

**Comment by esheldon** [comment]
I'm sorry I neglected this old pull request.  Do you have a version of this travis fix for OSX that will merge without conflicts?

**Comment by esheldon** [comment]
anyone want to try to re-implement this PR for testing on OSX?

**Comment by rainwoodman** [comment]
I think with the current master it becomes as simple as adding osx to .travis.yaml. We'll see if this is the case.

**Comment by rainwoodman** [comment]
I think this is ready to be merged. All green and minimal!

**Comment by esheldon** [comment]
thanks for the update

**Pull request merged**
