### PR TITLE
Added ignore_empty option to allow the writing of empty (no data) HDUs 0

### PR DESCRIPTION
**Pull request by menanteau**
Added kwarg to allow ignoring call to _ensure_empty_image_ok() function.

### CODE REVIEW

**Comment by esheldon** [comment]
Can we make it even simpler, just remove the `self._ensure_empty_image_ok()` altogether?

Or maybe we could make this an option on construction of the FITS object, defaulting to `allow_empty=True` ?

**Comment by menanteau** [comment]
We would remove `self._ensure_empty_image_ok() altogether`, but I guess the function was there for a reason

**Comment by esheldon** [comment]
It was there so that people would not write empty headers and then try to `fitsio.read(fname, ext=ext)` but maybe that isn't reallyl necessary

**Comment by esheldon** [comment]
actually I see that this was part of the write function, but I think it would be better in the constructor

**Comment by menanteau** [comment]
Sure, do you want to make the changes yourself?

**Comment by esheldon** [comment]
I think it would be easier for you to do it, then just push changes to your branch.  It will automatically update I think

**Comment by menanteau** [comment]
Just made the changes, but I'm not sure they were automatically updated.

**Pull request merged**
