### PR TITLE
don't run convert_keyword_to_allowed_ascii for HIERARCH header cards

### PR DESCRIPTION
**Pull request by dstndstn**
To address #325

### CODE REVIEW

**Comment by esheldon** [comment]
The pdf https://fits.gsfc.nasa.gov/registry/hierarch/hierarch.pdf makes it clear that there should be no "." in these names.

So this is a malformed header.  Did you identify what it was between 1.1.2 and 1.1.3 that causes it to fail?

**Comment by beckermr** [comment]
@dstndstn This one can be closed when you are ready. Happy to do it myself too.

**Comment by dstndstn** [comment]
Yes, thank you!

**Comment by dstndstn** [comment]
solved by #332 instead.

**Pull request closed without merging**
