### PR TITLE
Add bzip2 read support, part 2

### PR DESCRIPTION
**Pull request by dstndstn**
Various bug-fixes since the merge of #61

### CODE REVIEW

**Comment by esheldon** [comment]
Thanks very much Dustin for the bzip2 work

**Comment by esheldon** [comment]
@dstndstn did you ever get these patches into the main cfitsio?  I need to update the bundled version to the latest cfitsio but it is not in the latest official release

**Comment by dstndstn** [comment]
It was supposed to have been merged in CFITSIO v3.38 -- with "configure --with-bzip2", according to a 2015 email thread with the authors, but I haven't looked at the CFITSIO code to verify...

**Comment by esheldon** [comment]
I'm trying to wrap the latest and it is failing in the bzip test (branch cfitsio3420)

https://travis-ci.org/esheldon/fitsio/builds/318116765?utm_source=email&utm_medium=notification

**Comment by dstndstn** [comment]
umm, but it looks like it's failing somewhere unrelated, about a missing curl_global_cleanup symbol
https://travis-ci.org/esheldon/fitsio/jobs/318116768#L2118

**Comment by esheldon** [comment]
sorry, you are right.  It is failing tests on my local machine related to bzip

**Pull request merged**
