### PR TITLE
Add bzip2 read support

### PR DESCRIPTION
**Pull request by dstndstn**
The fitsio-specific parts from my old pull request #15 .

### CODE REVIEW

**Comment by dstndstn** [comment]
Don't pull this yet... need to check what happened upstream.  thx

**Comment by dstndstn** [comment]
So, it looks like the bulk of my bzip2-reading patches were not actually applied in 3.370.

This PR applies the required changes.  This makes the testBz2Read() test case pass; I also tested on a large FITS table compressed with bzip2.

**Comment by dstndstn** [comment]
These changes were also sent upstream (again).

**Comment by esheldon** [comment]
Thanks @dstndstn for these fixes.

If all the changes do not make it upstream, we may need to reapply your fixes to a new cfitsio release.  Can I count on you to do this if the need arises?

**Comment by dstndstn** [comment]
Hi @esheldon ,

This PR includes the required patches to the CFITSIO files: cfitsio3370/drvrfile.c and drvrmem.c (these are the patches I sent upstream).

After applying this PR, you should find that the test cases pass and that you can read bzip2-compressed FITS files.

**Comment by esheldon** [comment]
right, I understand, I just want to make sure we keep this functionality in case it never makes it upstream. For example, if a new cfitsio is released and we want to bundle it, we would have to apply the patches again to that.

**Comment by dstndstn** [comment]
Oh, yes, sure, I can do that. :)

**Comment by esheldon** [comment]
This doesn't compile for me

drvrmem.c:13:19: fatal error: bzlib.h: No such file or directory
 #include "bzlib.h"

I think you need to check for HAVE_BZLIB or something like that

**Comment by dstndstn** [comment]
That *is* inside a HAVE_BZIP2 protector:
https://github.com/dstndstn/fitsio/blob/bzip2/cfitsio3370/drvrmem.c#L12

Could you check what the cfitsio configure process printed out, especially about checking for bzlib.h?  I modified setup.py to run configure with "./configure --with-bzip2", which should check for that file and set HAVE_BZIP2 appropriately.

It really should use pkg-config, IMO, but I don't have that kind of configure-fu.

**Comment by esheldon** [comment]
I intentionally tried a machine without bzip2 installed, to make sure the code would still work

checking for bzlib.h... no

However, it then proceeds to set these anyway

-DHAVE_BZIP2=1 -DHAVE_STDLIB_H=1

looks like a bug in the configure script

**Comment by esheldon** [comment]
I think I'll probably have to roll back until we figure this out

**Comment by dstndstn** [comment]
Hi Erin,

Could you try now?  I just pushed another commit to my 'bzip2' branch;
https://github.com/dstndstn/fitsio/tree/bzip2

I tested without bzlib.h, with bzlib.h in a different place, etc, and it now seems to do the right thing.  But you should test too!

**Comment by esheldon** [comment]
On my system, the configure script didn't find bz and did not set DHAVE_BZIP2=1 etc.  However, it still tried to link so I get
```
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

**Comment by dstndstn** [comment]
Oops, I also had to conditionally include "bz2" in the setup.py list of libraries... Try now?
thanks for your patience!

**Comment by esheldon** [comment]
Two things.

On my system with bz, it is detected, HAVE_BZIP is set, and -lbz2 is set.  But I get this error
```
IOError: FITSIO status = 414: error uncompressing image
failed to uncompress file into memory (compress_open)
failed to find or open the following file: (ffopen)
blah.fits.bz
```
On my system *without* bz, it no longer tries to link.  I get an error trying to open the file
```
IOError: FITSIO status = 1: non-CFITSIO program error
failed to find or open the following file: (ffopen)
blah.fits.bz
```
I expected a more informative message, like "bzip2 files not supported.

**Comment by dstndstn** [comment]
For the first problem: it requires the suffix to be ".bz2", not ".bz".

For the second problem: aha, found the problem; I was checking for the "BZ"
compression signature even if HAVE_BZIP2 was not enabled.  Now, it should
just complain that it doesn't look like a FITS file (same message as when
you give it a text, mp3, or other non-FITS file).

**Comment by esheldon** [comment]
First problem:  But it tried to uncompress, doesn't that mean it knew it was
bz2?  Anyway, It would be nice if it could somehow detect it was bzip2 and say
exactly why it can't read, but this is certainly workable, thank you.

Second problem: yikes
```
>>>  t=fitsio.read('blah.fits.bz2', ext=1)
*** glibc detected *** /astro/u/esheldon/envs/conda-local/bin/python: realloc(): invalid next size: 0x00000000016cb150 ***
*** glibc detected *** /astro/u/esheldon/envs/conda-local/bin/python: malloc(): memory corruption: 0x00000000016cc0d0 ***
```
how to mix gdb and python extensions?

**Comment by parejkoj** [comment]
@dstndstn I know this is the pull request for fitsio, but are you tracking what went on with cfitsio somewhere? I'd like to follow that conversation too, thanks.

**Comment by dstndstn** [comment]
I've been emailing patches to ccfits@heasarc.gsfc.nasa.gov which I don't think has public archives.

**Comment by dstndstn** [comment]
@esheldon You could try valgrind... with python it's usually very messy, but it might show you where 
things have gone wrong.  Or can't you do
```
gdb --args python -c 'import fitsio; fitsio.read('blah.fits.bz2', ext=1)
```
?

I just checked the C program "tablist" linked to the fitsio-bundled libcfitsio.a, and it runs valgrind-clean for memory use on a bzip2'd FITS table.

**Comment by esheldon** [comment]
This part is related to your code I think
```
==24725== Invalid write of size 8
==24725==    at 0x4C29BF3: memcpy (mc_replace_strmem.c:882)
==24725==    by 0x12DE5DA2: mem_uncompress2mem (drvrmem.c:1106)
==24725==    by 0x12DE6FE8: mem_compress_open (drvrmem.c:700)
==24725==    by 0x12DE003D: ffopen (cfileio.c:727)
==24725==    by 0x12DE3387: ffopentest (cfileio.c:480)
==24725==    by 0x12DCFAFB: PyFITSObject_init (fitsio_pywrap.c:342)
==24725==    by 0x4EDA267: type_call (typeobject.c:745)
==24725==    by 0x4E77332: PyObject_Call (abstract.c:2529)
==24725==    by 0x4F264B1: PyEval_EvalFrameEx (ceval.c:4253)
==24725==    by 0x4F28DBD: PyEval_EvalCodeEx (ceval.c:3267)
==24725==    by 0x4EA6997: function_call (funcobject.c:526)
==24725==    by 0x4E77332: PyObject_Call (abstract.c:2529)
==24725==  Address 0x1399cb58 is 0 bytes after a block of size 3,960 alloc'd
==24725==    at 0x4C27BE0: realloc (vg_replace_malloc.c:662)
==24725==    by 0x12DE5D6D: mem_uncompress2mem (drvrmem.c:1098)
==24725==    by 0x12DE6FE8: mem_compress_open (drvrmem.c:700)
==24725==    by 0x12DE003D: ffopen (cfileio.c:727)
==24725==    by 0x12DE3387: ffopentest (cfileio.c:480)
==24725==    by 0x12DCFAFB: PyFITSObject_init (fitsio_pywrap.c:342)
==24725==    by 0x4EDA267: type_call (typeobject.c:745)
==24725==    by 0x4E77332: PyObject_Call (abstract.c:2529)
==24725==    by 0x4F264B1: PyEval_EvalFrameEx (ceval.c:4253)
==24725==    by 0x4F28DBD: PyEval_EvalCodeEx (ceval.c:3267)
==24725==    by 0x4EA6997: function_call (funcobject.c:526)
==24725==    by 0x4E77332: PyObject_Call (abstract.c:2529)
==24725== 
--24725-- VALGRIND INTERNAL ERROR: Valgrind received a signal 11 (SIGSEGV) - exiting
--24725-- si_code=80;  Faulting address: 0x0;  sp: 0x402f00de0

valgrind: the 'impossible' happened:
   Killed by fatal signal
==24725==    at 0x3803EC04: vgPlain_arena_malloc (m_mallocfree.c:291)
==24725==    by 0x3800386A: vgMemCheck_realloc (mc_malloc_wrappers.c:490)
==24725==    by 0x3807A0AD: vgPlain_scheduler (scheduler.c:1673)
==24725==    by 0x380A5A19: run_a_thread_NORETURN (syswrap-linux.c:103)
```

This is also worrying but not sure if it is directly related to fitsio
```
==24725== Conditional jump or move depends on uninitialised value(s)
==24725==    at 0x4EC442C: PyObject_Free (obmalloc.c:1013)
==24725==    by 0x4E8F52A: code_dealloc (codeobject.c:307)
==24725==    by 0x4F3CFAC: load_source_module (import.c:1104)
==24725==    by 0x4F3D7E9: load_package (import.c:1170)
==24725==    by 0x4F3DD40: import_submodule (import.c:2704)
==24725==    by 0x4F3DFB3: load_next (import.c:2519)
==24725==    by 0x4F3E61F: PyImport_ImportModuleLevel (import.c:2236)
==24725==    by 0x4F2048E: builtin___import__ (bltinmodule.c:49)
==24725==    by 0x4E77332: PyObject_Call (abstract.c:2529)
==24725==    by 0x4F20972: PyEval_CallObjectWithKeywords (ceval.c:3904)
==24725==    by 0x4F22FC2: PyEval_EvalFrameEx (ceval.c:2348)
==24725==    by 0x4F28DBD: PyEval_EvalCodeEx (ceval.c:3267)
==24725== 
==24725== Use of uninitialised value of size 8
==24725==    at 0x4EC4446: PyObject_Free (obmalloc.c:1013)
==24725==    by 0x4E8F52A: code_dealloc (codeobject.c:307)
==24725==    by 0x4F3CFAC: load_source_module (import.c:1104)
==24725==    by 0x4F3D7E9: load_package (import.c:1170)
==24725==    by 0x4F3DD40: import_submodule (import.c:2704)
==24725==    by 0x4F3DFB3: load_next (import.c:2519)
==24725==    by 0x4F3E61F: PyImport_ImportModuleLevel (import.c:2236)
==24725==    by 0x4F2048E: builtin___import__ (bltinmodule.c:49)
==24725==    by 0x4E77332: PyObject_Call (abstract.c:2529)
==24725==    by 0x4F20972: PyEval_CallObjectWithKeywords (ceval.c:3904)
==24725==    by 0x4F22FC2: PyEval_EvalFrameEx (ceval.c:2348)
==24725==    by 0x4F28DBD: PyEval_EvalCodeEx (ceval.c:3267)

```

**Comment by esheldon** [comment]
You are not using the memory writers/allocators.  Those use the reallocator pionter ->mem_realloc and automatically update the size etc.  Not sure if this matters or not.

**Comment by esheldon** [comment]
OK, the following works
```
            if (bzerror == BZ_OK || bzerror == BZ_STREAM_END) {
                mem_write(hdl, buf, nread);
                offset += nread;
            }

```

**Comment by dstndstn** [comment]
Aha, excellent!

(But I tried doing that, and now the reading bzip2 test case fails...)

I'm offline for a couple of hours but will see if I can get this working
after that.

thx

**Comment by esheldon** [comment]
Interesting, the tests work for me

**Comment by dstndstn** [comment]
Apologies, I wasn't running the version I thought I was running.  I confirm that the test passes with this change.  I pushed a slightly cleaned-up version.
Finally good to go? :)

**Comment by esheldon** [comment]
I think so.

For pushing this to W. Pence, it might be more palatable if this section was pulled into a short function, that matches the signature of the others, e.g. zuncompress2mem

**Comment by dstndstn** [comment]
Good point; done.

**Comment by esheldon** [comment]
Sorry, one more thing.  We should probably make a new directory cfitsio3370patch for this so it is clear we are not using stock 3370

**Comment by dstndstn** [comment]
just rename the directory?

**Comment by esheldon** [comment]
(I will remove the old cfitsio3280patch and cfitsio3370 after I merge, to clean things up)

**Comment by esheldon** [comment]
actually, yes a rename is fine

**Comment by parejkoj** [comment]
@dstndstn can you please Cc: me on any upstream emails? I'd like to test any beta release of cfitsio.

**Comment by dstndstn** [comment]
done

**Comment by esheldon** [comment]
Works for me.  But on my system without bz2 the test fails.  Is there a way to detect if bz2 is supported and not run the test?

**Comment by dstndstn** [comment]
hmmm... no easy test I can think of...

**Comment by esheldon** [comment]
OK, I'll put something in the README saying that some tests will fail if certain libraries are not detected, and this is OK

Will this version merge cleanly over what I already accepted before?

**Comment by dstndstn** [comment]
It should... it's all on the same branch

**Comment by esheldon** [comment]
OK, then please send a new pull request

**Pull request merged**
