### PR TITLE
read_raw

### PR DESCRIPTION
**Pull request by dstndstn**
This PR adds a read_raw() method to the fitsio_pywrap.c FITS class.  It flushes data, copies the full file contents, and returns it as a Python string.

This should be particularly useful for "mem://" files.

This is motivated by a kind of weird use case where we want to catch filesystem corruption, so we do:

```
F = fitsio.FITS('mem://', 'rw')
F.write( ... )
rawdata = F.read_raw()
sha = hashlib.sha1()
sha.update(rawdata)
# remember sha.hexdigest()
f=open('F.fits', 'w')
f.write(rawdata)
f.close()
# Run sha1sum F.fits, compare against sha.hexdigest().
```

### CODE REVIEW

**Comment by esheldon** [comment]
Thanks Dustin.  Let me know when you think this is ready for review

**Comment by dstndstn** [comment]
I *thought* it was ready when I submitted the PR, but then Travis got mad at me (correctly) for Py3 problems.  That's fixed, so I think it's good to go now.  I also checked that I got the memory management right.  Thanks!

**Comment by dstndstn** [comment]
Ready for review :)

**Comment by esheldon** [comment]
this looks good to me, no need for a full review

**Comment by dstndstn** [comment]
Thank you!

**Pull request merged**
