### PR TITLE
write long long rather than long

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by esheldon** [comment]
travis is not triggering

**Comment by at88mph** [comment]
Awesome, thanks.  I realize this is likely a bad database ID that was used to generate the file or something, so much obliged.

**Comment by esheldon** [comment]
huh... travis is actually running, it just isn't showing up here

**Comment by at88mph** [comment]
I've noticed that GitHub now prefers you to create their Actions rather than use Travis these days.

**Comment by esheldon** [comment]
there is now an incident for the CI problem:  https://www.githubstatus.com/

**Comment by esheldon** [comment]
they claim to have fixed it but it is not fixed

I'm starting to think there is a problem with travis because, for example, mac os builds are not starting

**Comment by esheldon** [comment]
It ran and succeeded, gonna merge

**Pull request merged**
