### PR TITLE
Replace depreacted numpy.bool with numpy.bool_

### PR DESCRIPTION
**Pull request by erykoff**

### CODE REVIEW

**Comment by beckermr** [comment]
Will this work with older numpy versions too?

**Comment by beckermr** [comment]
Any comments @esheldon?

**Comment by esheldon** [comment]
I think the recommendation is to use regular `bool` for this, e.g.
```python
np.zeros(num, dtype=bool)
```

**Comment by esheldon** [comment]
https://numpy.org/devdocs/release/1.20.0-notes.html

See "deprecated".  It recommends using the second column rather than the third

**Comment by erykoff** [comment]
I'm not sure if `numpy.bool_` vs `bool` matters much, but either will work.  I also forgot to update `table.py`.

**Comment by erykoff** [comment]
I also confirmed that you can do dtype equivalence with `bool`, `numpy.bool_` or `numpy.bool` (the final one with a deprecation warning on 1.20).

**Comment by esheldon** [comment]
any interest to add a bool test?  If not that's ok

**Comment by erykoff** [comment]
Wasn't planning on it.  It's that right now whenever I see a warning here I do a drive-by PR to fix things (including, of course, my own code...)

**Comment by beckermr** [comment]
I'm all for drive-by PRs. They make the world a better place.

**Pull request merged**
