### PR TITLE
fixes for writing comments with blank keywords

### LINKED ISSUE #249: Writing comments with blank keywords
At LSST we wish to construct headers that look like this:

```
ORIGIN  = 'LSST DM Header Service'/ FITS file originator

         ---- Date, night and basic image information ----
DATE-OBS=   '2019-10-10T05:40' / Date of the observation (image acquisition)
```

These are fully compliant with the FITS standard where section 4.4.2.4 of https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf says:

> Keyword field is blank. This keyword may be used to supply any comments regarding the FITS file. It is frequently used for aesthetic purposes to provide a break between groups of related keywords in the header.

but we can't work out how to call `fitsio` such that we get the blank keyword. Calling `write_key` with an keyword of spaces or a keyword of `None` doesn't work since you either get the blank with an `=` sign, or you get `NONE     =`.  What are we missing?

### PR DESCRIPTION
**Pull request by esheldon**
closes #249 

the current version writes them correctly when adding cards as a dict

todo
- [x] add tests
- [x] add writing from cards
- [x] they currently get read back as empty comments, yet another casualty of the header reading optimizations

### CODE REVIEW

**Comment by timj** [comment]
This looks good to me (I haven't tested it). @menanteau can you take a look?

**Comment by esheldon** [comment]
this won't affect the case of @menanteau , I already fixed that in a different PR

**Comment by timj** [comment]
Right, but I mean that @menanteau is the person who is dealing with the LSST side that this fix is required for. 😄

**Comment by esheldon** [comment]
@timj @menanteau this I think addresses the issue

**Comment by esheldon** [comment]
The branch is blank-key

**Comment by esheldon** [comment]
I'd like to see if this does what you need before merging this PR

**Comment by menanteau** [comment]
@esheldon Thanks! I will give a try soon.

**Comment by menanteau** [comment]
@esheldon I tested and it works! However, there is a small change on the expected behavior. A section of the original input header was:
```
ORIGIN  = 'LSST DM Header Service'/ FITS file originator
         ---- Date, night and basic image information ----
DATE    =                      / Creation Date and Time of File
```
And the same section now looks like this:
```
ORIGIN  = 'LSST DM Header Service' / FITS file originator 
        ---- Date, night and basic image information ----                       
DATE    = '2019-05-30T22:17:08.423' / Creation Date and Time of File    
```

Note that the 'blank' comment is shifted by one space to the left in the output (i.e. it is now aligned with the `=` sign.

**Comment by esheldon** [comment]
thanks, this was in the code to process input string cards. I've fixed it, please give it a try.

**Comment by esheldon** [comment]
This was an interesting case of offsetting bugs:  I had mis-formatted my unit test in just such a way that it offset this bug.  I think there is a lesson here about confirmation bias.

**Comment by menanteau** [comment]
Thanks @esheldon. I can confirm that it works as desired. Could you merge the `blank-key` branch and tag the merge, so I can install from that tag.

**Pull request merged**
