### PR TITLE
#207 fix issues converting string header entries

### PR DESCRIPTION
**Pull request by esheldon**
If the entry is a string, don't even try to convert it.

Also remove extra convert attempt; this is not needed because conversion happens in the FITSCard

### CODE REVIEW

**Comment by esheldon** [comment]
@dstndstn the CI has passed, will you have a chance to test it out or should I just merge it?

**Comment by dstndstn** [comment]
Hi @esheldon , Thanks for the amazingly fast turn-around!  @moustakas (who diagnosed this) is checkout out this solution, so if you can hold on an hour, can confirm the fix.  Thanks again!

**Comment by esheldon** [comment]
Of course, no hurry from my end.

**Comment by moustakas** [comment]
Just tested and works like a charm, thank you @esheldon!

**Comment by esheldon** [comment]
you're welcome!

**Pull request merged**
