### PR TITLE
removed -iarch in setup.py

### PR DESCRIPTION
**Pull request by cbonnett**
This should do the job

### CODE REVIEW

**Comment by menanteau** [comment]
Not sure if this is necessary.  For DESDM we have compiled and installed without problem for 10.7-10.9 for a while now, using clang -- not CC.

**Comment by esheldon** [comment]
@menanteau see issue #2   This seems to help some users.  Do you see a problem?

**Comment by esheldon** [comment]
in other words, would it break the clang build?

**Comment by menanteau** [comment]
Likely, as clang-compiled binaries are most of the time compiled again libraries that where also compiled in a universal way

**Comment by esheldon** [comment]
OK, then we need a test for this in setup.py

**Pull request merged**
